# Generated by Django 4.1.3 on 2022-12-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'ordering': ['-time', 'title']},
        ),
        migrations.RenameField(
            model_name='base',
            old_name='fetched',
            new_name='generated',
        ),
        migrations.AlterField(
            model_name='base',
            name='by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
